export const CREATE_ROW = 'THERON:CREATE_ROW';
export const REMOVE_ROW = 'THERON:REMOVE_ROW';
export const UPDATE_ROW = 'THERON:UPDATE_ROW';

export const ROW_CREATED = 'THERON:ROW_CREATED';
export const ROW_REMOVED = 'THERON:ROW_REMOVED';
export const ROW_UPDATED = 'THERON:ROW_UPDATED';

export const SUBSCRIBE_QUERY = 'THERON:SUBSCRIBE_QUERY';
export const UNSUBSCRIBE_QUERY = 'THERON:UNSUBSCRIBE_QUERY';

export const QUERY_ERROR = 'THERON:QUERY_ERROR';
export const QUERY_READY = 'THERON:QUERY_READY';
export const QUERY_INITIALIZING = 'THERON:QUERY_INITIALIZING';
export const QUERY_VALID = 'THERON:QUERY_VALID';
export const QUERY_INVALID = 'THERON:QUERY_INVALID';
