export const CREATE_ROW = 'THERON:CREATE_ROW';
export const REMOVE_ROW = 'THERON:REMOVE_ROW';
export const UPDATE_ROW = 'THERON:UPDATE_ROW';

export const ROW_CREATED = 'THERON:ROW_CREATED';
export const ROW_REMOVED = 'THERON:ROW_REMOVED';
export const ROW_UPDATED = 'THERON:ROW_UPDATED';

export const UPSERT_QUERY = 'THERON:UPSERT_QUERY';
export const REMOVE_QUERY = 'THERON:REMOVE_QUERY';
export const DISPATCH_QUERY = 'THERON:DISPATCH_QUERY';
export const WATCH_QUERY = 'THERON:WATCH_QUERY';
export const SUBSCRIBE_QUERY = 'THERON:SUBSCRIBE_QUERY';
export const UNSUBSCRIBE_QUERY = 'THERON:UNSUBSCRIBE_QUERY';

export const QUERY_VALID = 'THERON:QUERY_VALID';
export const QUERY_INVALID = 'THERON:QUERY_INVALID';
export const QUERY_READY = 'THERON:QUERY_READY';
export const QUERY_ERROR = 'THERON:QUERY_ERROR';

export const PARSE_ERROR = 'THERON:PARSE_ERROR';

export const REQUEST_SUCCESS = 'THERON:REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'THERON:REQUEST_FAILURE';
