export const SUBSCRIBE_QUERY = 'TN:SUBSCRIBE_QUERY';
export const UNSUBSCRIBE_QUERY = 'TN:UNSUBSCRIBE_QUERY';

export const REQUEST_SUCCESS = 'TN:REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'TN:REQUEST_FAILURE';

export const ROW_ADDED = 'TN:ROW_ADDED';
export const ROW_REMOVED = 'TN:ROW_REMOVED';
export const ROW_MOVED = 'TN:ROW_MOVED';
export const ROW_CHANGED = 'TN:ROW_CHANGED';
